### ISSUE TITLE
isInCombat(Player) is undefined for type CombatUtil - 2.42

### ISSUE THREAD

**Issue by Benlewis9000** [gronnmann/CoinFlipper#10]
Running CoinFlipper 2.42 and paperspigot 1.8.8, starting a game spammed the console with this error:

```
[16:38:23 WARN]: [CoinFlipper] Task #50775 for CoinFlipper v2.42 generated an exception
java.lang.Error: Unresolved compilation problem:
        The method isInCombat(Player) is undefined for the type CombatUtil

        at io.github.gronnmann.coinflipper.hook.HookCombatLogX.isTagged(HookCombatLogX.java:18) ~[?:?]
        at io.github.gronnmann.coinflipper.hook.HookManager.isTagged(HookManager.java:97) ~[?:?]
        at io.github.gronnmann.coinflipper.animations.AnimationRunnable.run(AnimationRunnable.java:58) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

The game never starts/completes so the two players involved can't compete in any other games, as they are technically still in a game.

**Comment by gronnmann** [comment]
Are you using the latest version of CombatTagX? They have changed their API quite a bit between versions.

**Comment by Benlewis9000** [comment]
I'm not - this was on CombatLogX 9.7.1.3.

I'll update to 9.8.2.2 now, reenable coinflipper and let you know how it goes.

**Comment by Benlewis9000** [comment]
The issue seems to be gone - thank you very much!

(updated CombatLogX and CF to v2.43)

**Comment by gronnmann** [comment]
No problem, glad I could be of help.
