### ISSUE TITLE
CombatLogX error

### ISSUE THREAD

**Issue by Projecki** [gronnmann/CoinFlipper#17]
>.... [19:31:12 WARN]: [CoinFlipper] Task #17487 for CoinFlipper v2.7 generated an exception
java.lang.NoClassDefFoundError: com/SirBlobman/combatlogx/utility/CombatUtil
at io.github.gronnmann.coinflipper.hook.HookCombatLogX.isTagged(HookCombatLogX.java:18) ~[?:?]
at io.github.gronnmann.coinflipper.hook.HookManager.isTagged(HookManager.java:108) ~[?:?]
at io.github.gronnmann.coinflipper.animations.AnimationRunnable.run(AnimationRunnable.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:376) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by gronnmann** [comment]
This should be fixed with 2.8, which will be released tomorrow.
