### ISSUE TITLE
Hook - CombatLogX

### ISSUE THREAD

**Issue by JorisPV** [gronnmann/CoinFlipper#24]
Hello,

Can you update the compatibility with CombatLogX to the latest update? Because it is no longer compatible with the last dev-build of CombatlogX.
https://github.com/gronnmann/CoinFlipper/blob/master/src/io/github/gronnmann/coinflipper/hook/HookCombatLogX.java

Error: [16:22:39] [Server thread/INFO]: [CoinFlipper] CombatLogX detected. Hooking...
[16:22:39] [Server thread/ERROR]: Error occurred while enabling CoinFlipper v2.92 (Is it up to date?)
java.lang.NoClassDefFoundError: com/SirBlobman/combatlogx/api/ICombatLogX
	at io.github.gronnmann.coinflipper.hook.HookCombatLogX.register(HookCombatLogX.java:21) ~[?:?]
	at io.github.gronnmann.coinflipper.hook.HookManager.setHooked(HookManager.java:81) ~[?:?]
	at io.github.gronnmann.coinflipper.hook.HookManager.registerHooks(HookManager.java:56) ~[?:?]
	at io.github.gronnmann.coinflipper.CoinFlipper.onEnable(CoinFlipper.java:60) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:398) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:363) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:322) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:445) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:409) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:364) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:285) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:615) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: com.SirBlobman.combatlogx.api.ICombatLogX
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 15 more
[16:22:39] [Server thread/INFO]: [CoinFlipper] Disabling CoinFlipper v2.92
Poke @SirBlobman 
Thanks you :)

Best regards,

**Comment by SirBlobman** [comment]
@Acenox 
Thanks for the request, I'll add that to my to-do list unless someone else makes a pull request first. For now I recommend using a stable build if you want to use the CoinFlipper hook.
