### ISSUE TITLE
Click Event

### ISSUE THREAD

**Issue by EvilSlime** [gronnmann/CoinFlipper#6]
[12:35:49] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CoinFlipper v2.1org.bukkit.event.EventExceptionat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: java.lang.NullPointerExceptionat io.github.gronnmann.coinflipper.gui.SelectionScreen.detectClicks(SelectionScreen.java:288) ~[?:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]... 16 more

**Comment by gronnmann** [comment]
Looks like you somehow screwed up the animation config. Could you post your animation .yml file and the config.yml ?

Also, from version 2.3 and onwards, this bug should be fixed.
