### ISSUE TITLE
NPE on /coinflipper convert

### ISSUE THREAD

**Issue by Benlewis9000** [gronnmann/CoinFlipper#8]
Convert fails, and I was directed to console, where I saw this:

```
[23:00:12 INFO]: Anarchist issued server command: /coinflipper convert
[23:00:12 WARN]: java.lang.NullPointerException
[23:00:12 WARN]:        at io.github.gronnmann.coinflipper.stats.StatsManager.convertToSQLite(StatsManager.java:160)
[23:00:12 WARN]:        at io.github.gronnmann.coinflipper.CommandsManager.onCommand(CommandsManager.java:169)
[23:00:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:00:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[23:00:12 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:00:12 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:00:12 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[23:00:12 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[23:00:12 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by gronnmann** [comment]
Do you have your stats.yml file?
The issue seems kinda weird to me

**Comment by Benlewis9000** [comment]
My stats.yml was empty - I have since deleted this and am assuming it will now just save them to the database as intended?

**Comment by gronnmann** [comment]
Yup, the command is intented for when you have a stats.yml file filled with data and want to convert that data to the SQLite storage. If the file is empty - theres nothing to convert.

But anyways, a fix to the NPE appearing is coming to the next patch.
